name: Build Windows Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Cambia esto a la versión de Python que usas

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Build executable
      run: |
        pyinstaller --onefile --add-data "logo_base64.txt;." carrousel.py

    - name: Compress executable to ZIP
      run: |
        powershell Compress-Archive -Path dist/carrousel.exe -DestinationPath dist/carrousel.zip

    - name: Upload ZIP
      uses: actions/upload-artifact@v3
      with:
        name: Carrousel-Executable-ZIP
        path: dist/carrousel.zip
